### ISSUE TITLE
USPS sensor broken on 0.42?

### ISSUE THREAD

**Issue by brianjking** [brianjking/homeassistant-config#71]

**Comment by brianjking** [comment]
```
17-04-09 12:16:11 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform usps
Traceback (most recent call last):
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/helpers/entity_component.py", line 153, in _async_setup_platform
    entity_platform.schedule_add_entities, discovery_info
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/components/sensor/usps.py", line 54, in setup_platform
    config.get(CONF_UPDATE_INTERVAL))])
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/components/sensor/usps.py", line 69, in __init__
    self.update()
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/util/__init__.py", line 296, in wrapper
    result = method(*args, **kwargs)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/components/sensor/usps.py", line 85, in _update
    for package in myusps.get_packages(self._session):
  File "/home/homeassistant/.homeassistant/deps/myusps/__init__.py", line 106, in wrapped
    return function(*args)
  File "/home/homeassistant/.homeassistant/deps/myusps/__init__.py", line 141, in get_packages
    'date': str(parse(' '.join(row.xpath(DATE_XPATH)[0].text.split()))),
  File "/home/homeassistant/.homeassistant/deps/dateutil/parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/homeassistant/.homeassistant/deps/dateutil/parser.py", line 562, in parse
    raise ValueError("String does not contain a date.")
ValueError: String does not contain a date.
```

**Comment by brianjking** [comment]
Reported in Home Assistant issue tracker at https://github.com/home-assistant/home-assistant/issues/7002.

**Comment by brianjking** [comment]
https://github.com/home-assistant/home-assistant/issues/7002#issuecomment-292935935
